/**
 * Catálogo de KPIs del piloto (A3.1 técnicos, A3.2 UX y pedagógicos, A3.3
 * operacionalización, A3.5 umbrales y A3.6 reporte).
 *
 * Es la fuente de verdad: `src/services/kpis.ts` calcula los automáticos con
 * estas definiciones y `npm run kpis:catalogo` genera
 * `docs/metricas/catalogo-kpis.md`. Si cambia un umbral, se cambia aquí.
 *
 * Regla para las contradicciones del anteproyecto: manda la sección 5.4, que
 * es la tabla de KPIs (latencia ≤ 8 s y no ≤ 10 s; mejoras ≥ 65 % y no ≥ 70 %).
 * Los umbrales «propuestos» no están en el anteproyecto y los aprueba el
 * director antes del piloto (A3.5, A5.7).
 */

export type KpiDimension = "tecnico" | "ux" | "pedagogico";
export type KpiSource = "telemetria" | "encuesta" | "asistencia" | "registro" | "pruebas" | "catalogo" | "quices";
export type KpiObjective = "OE1" | "OE2" | "OE3";

export type KpiThreshold = {
  op: "<=" | ">=" | "=";
  value: number;
};

export type KpiDefinition = {
  id: string;
  name: string;
  dimension: KpiDimension;
  objective: KpiObjective;
  /** Uno de los KPI principales del anteproyecto (al menos uno por dimensión). */
  primary: boolean;
  question: string;
  formula: string;
  unit: string;
  window: string;
  sources: KpiSource[];
  events: string[];
  /** null: KPI descriptivo, se reporta sin umbral. */
  threshold: KpiThreshold | null;
  thresholdText: string;
  origin: string;
  /** Decisión tomada al operacionalizar (contradicciones, línea base, exclusiones). */
  decision: string;
  /** Se calcula solo con npm run piloto:analisis; si no, se registra a mano. */
  automatic: boolean;
  /** Cómo se muestra en el reporte (A3.6). */
  chart: string;
  jira: string[];
};

export const KPI_DIMENSION_LABEL: Record<KpiDimension, string> = {
  tecnico: "Técnicos",
  ux: "Experiencia de uso (UX)",
  pedagogico: "Pedagógicos",
};

export const KPI_SOURCE_LABEL: Record<KpiSource, string> = {
  telemetria: "telemetría (telemetry_events)",
  encuesta: "encuesta final (A13.2)",
  asistencia: "lista de asistencia y consentimientos",
  registro: "registro manual",
  pruebas: "pruebas de humo",
  catalogo: "catálogo de eventos",
  quices: "intentos del mini-quiz",
};

export const KPI_CATALOG: KpiDefinition[] = [
  // --- Técnicos (A3.1) --------------------------------------------------------
  {
    id: "T1",
    name: "Latencia del tutor (mediana)",
    dimension: "tecnico",
    objective: "OE2",
    primary: true,
    question: "¿Cuánto espera el estudiante por una ayuda del tutor?",
    formula: "Mediana (p50) de latency_ms de los eventos tutor_decision con blocked = false y sin caché, en segundos. Percentil con interpolación lineal (PERCENTIL.INC).",
    unit: "s",
    window: "Cada sesión y el piloto completo; por canal (overlay y VS Code).",
    sources: ["telemetria"],
    events: ["tutor_decision"],
    threshold: { op: "<=", value: 8 },
    thresholdText: "≤ 8 s",
    origin: "Anteproyecto 5.4 (arquitectura híbrida).",
    decision: "El anteproyecto dice ≤ 8 s en 5.4 y ≤ 10 s en A9; manda 5.4. La latencia es la del servidor (de la petición a la respuesta), no incluye la red de la sala.",
    automatic: true,
    chart: "Diagrama de caja por canal; p50 y p95 por sesión en una tabla.",
    jira: ["A3.1", "A3.3", "A12.2"],
  },
  {
    id: "T2",
    name: "Latencia del tutor (p95)",
    dimension: "tecnico",
    objective: "OE2",
    primary: false,
    question: "¿Cuánto esperan los casos lentos?",
    formula: "Percentil 95 de la misma serie de T1, en segundos.",
    unit: "s",
    window: "Cada sesión y el piloto completo; por canal.",
    sources: ["telemetria"],
    events: ["tutor_decision"],
    threshold: { op: "<=", value: 15 },
    thresholdText: "≤ 15 s",
    origin: "Propuesto: el anteproyecto no fija un p95.",
    decision: "15 s deja margen para el sondeo de la cola (8 s) sobre la inferencia en caliente medida (2 a 7 s).",
    automatic: true,
    chart: "Junto con T1 en el diagrama de caja.",
    jira: ["A3.1", "A3.5", "A12.2"],
  },
  {
    id: "T3",
    name: "Respuestas del tutor sin fallo",
    dimension: "tecnico",
    objective: "OE2",
    primary: false,
    question: "¿Qué parte de las ayudas llega del modelo y no del respaldo por falla?",
    formula: "1 − (decisiones con reason_code = model_error_fallback / decisiones no bloqueadas sin caché).",
    unit: "%",
    window: "Cada sesión y el piloto completo.",
    sources: ["telemetria"],
    events: ["tutor_decision"],
    threshold: { op: ">=", value: 95 },
    thresholdText: "≥ 95 %",
    origin: "Propuesto a partir de «cero fallos críticos» (A9, A10) y «funcionalidad del MVP ≥ 95 %» (5.4).",
    decision: "Una respuesta degradada (sin worker) cuenta como fallo aunque el estudiante reciba un mensaje controlado.",
    automatic: true,
    chart: "Semáforo en la tabla de KPIs.",
    jira: ["A3.1", "A3.5"],
  },
  {
    id: "T4",
    name: "Pérdida de eventos",
    dimension: "tecnico",
    objective: "OE2",
    primary: false,
    question: "¿Se pierde telemetría entre el cliente y la base?",
    formula: "Eventos faltantes por huecos de seq / eventos esperados, por client_session_id (regla I1).",
    unit: "%",
    window: "Cada sesión y el piloto completo.",
    sources: ["telemetria"],
    events: ["(todos los eventos con seq)"],
    threshold: { op: "<=", value: 2 },
    thresholdText: "≤ 2 %",
    origin: "Propuesto.",
    decision: "Solo cuenta a los clientes que numeran sus eventos (overlay y VS Code); los del backend no llevan seq.",
    automatic: true,
    chart: "Semáforo; en vivo, alerta del monitor.",
    jira: ["A3.1", "A3.5", "A14.2"],
  },
  {
    id: "T5",
    name: "Eventos duplicados",
    dimension: "tecnico",
    objective: "OE2",
    primary: false,
    question: "¿Llegan eventos repetidos?",
    formula: "Eventos con el mismo client_session_id y seq / eventos con seq (regla I2).",
    unit: "%",
    window: "Cada sesión y el piloto completo.",
    sources: ["telemetria"],
    events: ["(todos los eventos con seq)"],
    threshold: { op: "<=", value: 1 },
    thresholdText: "≤ 1 %",
    origin: "Propuesto.",
    decision: "En la limpieza (A14.3) se conserva el primero y se descartan las copias.",
    automatic: true,
    chart: "Semáforo.",
    jira: ["A3.1", "A3.5", "A14.3"],
  },
  {
    id: "T6",
    name: "Sesiones con telemetría",
    dimension: "tecnico",
    objective: "OE3",
    primary: false,
    question: "¿Se registró el trabajo de los estudiantes que asistieron?",
    formula: "Estudiantes con al menos un evento con condición del piloto en la fecha / estudiantes presentes según la asistencia, sumado sobre las sesiones.",
    unit: "%",
    window: "Cada sesión del piloto.",
    sources: ["telemetria", "asistencia"],
    events: ["(eventos con pilot_condition)"],
    threshold: { op: ">=", value: 90 },
    thresholdText: "≥ 90 %",
    origin: "Anteproyecto 5.4 (telemetría en ≥ 90 % de las sesiones).",
    decision: "La asistencia entra como conteo por sesión (sin nombres). Un estudiante sin la sesión compartida de VS Code configurada no tiene condición y cuenta como sesión sin telemetría.",
    automatic: true,
    chart: "Barras por sesión: presentes contra estudiantes con telemetría.",
    jira: ["A3.1", "A14.1"],
  },
  {
    id: "T7",
    name: "Incidentes críticos en clase",
    dimension: "tecnico",
    objective: "OE2",
    primary: false,
    question: "¿El sistema dejó a la clase sin trabajar?",
    formula: "Incidentes de severidad 1 del registro del plan de soporte durante las sesiones.",
    unit: "incidentes",
    window: "Piloto completo.",
    sources: ["registro"],
    events: [],
    threshold: { op: "=", value: 0 },
    thresholdText: "= 0",
    origin: "Anteproyecto (A9 y A10: cero fallos críticos).",
    decision: "Severidad 1 = la clase o más de la mitad del grupo no puede seguir trabajando (ver plan de soporte).",
    automatic: false,
    chart: "Tabla de incidentes por sesión.",
    jira: ["A3.1", "A13.5"],
  },
  {
    id: "T8",
    name: "Pruebas de humo",
    dimension: "tecnico",
    objective: "OE2",
    primary: false,
    question: "¿Funciona el MVP de punta a punta antes de cada sesión?",
    formula: "Comprobaciones correctas de npm run demo:escenarios contra producción / comprobaciones totales.",
    unit: "%",
    window: "Antes de cada sesión.",
    sources: ["pruebas"],
    events: [],
    threshold: { op: ">=", value: 95 },
    thresholdText: "≥ 95 %",
    origin: "Anteproyecto 5.4 (funcionalidad del MVP ≥ 95 % en pruebas de humo).",
    decision: "Se registra la de cada sesión; el KPI es la peor.",
    automatic: false,
    chart: "Tabla por sesión.",
    jira: ["A3.1", "A12.1"],
  },
  {
    id: "T9",
    name: "Respuestas ancladas en material autorizado",
    dimension: "tecnico",
    objective: "OE2",
    primary: false,
    question: "¿El tutor responde con el material del curso?",
    formula: "Decisiones no bloqueadas con al menos una fuente autorizada (metadata.ragSources ≥ 1) / decisiones no bloqueadas de eventos del curso.",
    unit: "%",
    window: "Piloto completo; por canal.",
    sources: ["telemetria"],
    events: ["tutor_decision"],
    threshold: { op: ">=", value: 80 },
    thresholdText: "≥ 80 %",
    origin: "Anteproyecto 5.4 (≥ 80 % de respuestas ancladas cuando aplica).",
    decision: "«Cuando aplica» = eventos del curso: se excluyen out_of_domain y las consultas de flujo de trabajo (git, GitHub). Con fuentes, la cita es obligatoria (ensureMentorResultRagCitations).",
    automatic: true,
    chart: "Semáforo por canal.",
    jira: ["A3.1", "A8.6"],
  },
  {
    id: "T10",
    name: "Tiempo de instalación",
    dimension: "tecnico",
    objective: "OE2",
    primary: false,
    question: "¿Un estudiante nuevo queda listo en poco tiempo?",
    formula: "Mediana de los minutos desde abrir la guía hasta tener el overlay con sesión y el editor por túnel con ADACEEN, en la validación de la guía (A16.8).",
    unit: "min",
    window: "Validación de la guía.",
    sources: ["registro"],
    events: [],
    threshold: { op: "<=", value: 15 },
    thresholdText: "≤ 15 min",
    origin: "Anteproyecto (guía de instalación y uso, instalación ≤ 15 min).",
    decision: "Se cronometra con al menos 3 personas que no conocen el proyecto.",
    automatic: false,
    chart: "Tabla de tiempos por persona.",
    jira: ["A3.1", "A16.8"],
  },
  {
    id: "T11",
    name: "Cumplimiento de privacidad, ética y seguridad",
    dimension: "tecnico",
    objective: "OE1",
    primary: false,
    question: "¿El piloto cumple lo prometido en datos y ética?",
    formula: "Ítems cumplidos / ítems aplicables de la lista de cumplimiento (A13.4).",
    unit: "%",
    window: "Antes del piloto.",
    sources: ["registro"],
    events: [],
    threshold: { op: ">=", value: 80 },
    thresholdText: "≥ 80 %",
    origin: "Anteproyecto (A5 y A13.4: checklist ≥ 80 %).",
    decision: "Los ítems críticos (consentimiento, seudonimización, sal configurada) son obligatorios aunque el total pase del 80 %.",
    automatic: false,
    chart: "Tabla de la lista con su estado.",
    jira: ["A3.1", "A13.4"],
  },
  {
    id: "T12",
    name: "Eventos útiles en el diccionario",
    dimension: "tecnico",
    objective: "OE1",
    primary: false,
    question: "¿La telemetría tiene suficientes eventos con propósito?",
    formula: "Eventos del catálogo que alimentan al menos un KPI.",
    unit: "eventos",
    window: "Versión del diccionario.",
    sources: ["catalogo"],
    events: [],
    threshold: { op: ">=", value: 10 },
    thresholdText: "≥ 10",
    origin: "Anteproyecto (A4: al menos 10 eventos útiles).",
    decision: "Se cuenta desde src/services/telemetry-catalog.ts.",
    automatic: true,
    chart: "Número en la tabla de KPIs.",
    jira: ["A3.1", "A4.1"],
  },

  // --- Experiencia de uso (A3.2) ----------------------------------------------
  {
    id: "U1",
    name: "Experiencia de uso del tutor",
    dimension: "ux",
    objective: "OE3",
    primary: true,
    question: "¿A los estudiantes les resultó cómodo y útil trabajar con el tutor?",
    formula: "Promedio de los ítems UX1 a UX6 de la encuesta final (escala de 1 a 5), primero por persona y luego entre personas.",
    unit: "/5",
    window: "Al final del piloto.",
    sources: ["encuesta"],
    events: [],
    threshold: { op: ">=", value: 4 },
    thresholdText: "≥ 4,0 / 5",
    origin: "Anteproyecto 5.4 (UX ≥ 4/5).",
    decision: "Se reporta también la distribución por ítem; una persona cuenta si respondió al menos 4 de los 6 ítems.",
    automatic: true,
    chart: "Barras divergentes por ítem (de «totalmente en desacuerdo» a «totalmente de acuerdo»).",
    jira: ["A3.2", "A13.2"],
  },
  {
    id: "U2",
    name: "Usabilidad (SUS)",
    dimension: "ux",
    objective: "OE3",
    primary: false,
    question: "¿Qué tan usable es el sistema frente a una referencia estándar?",
    formula: "Puntaje SUS de 0 a 100 por persona (ítems impares: valor − 1; pares: 5 − valor; suma × 2,5) y su promedio.",
    unit: "puntos",
    window: "Al final del piloto.",
    sources: ["encuesta"],
    events: [],
    threshold: { op: ">=", value: 68 },
    thresholdText: "≥ 68",
    origin: "Propuesto: 68 es el promedio de referencia de la escala SUS.",
    decision: "Solo cuentan las encuestas con los 10 ítems SUS respondidos.",
    automatic: true,
    chart: "Histograma de puntajes SUS.",
    jira: ["A3.2", "A13.2"],
  },
  {
    id: "U3",
    name: "Ayudas valoradas como útiles",
    dimension: "ux",
    objective: "OE3",
    primary: false,
    question: "¿En el momento, las ayudas le sirvieron al estudiante?",
    formula: "«Me sirvió» / («Me sirvió» + «No me sirvió») en el overlay (tutor_response_accepted y tutor_response_rejected).",
    unit: "%",
    window: "Piloto completo.",
    sources: ["telemetria"],
    events: ["tutor_response_accepted", "tutor_response_rejected"],
    threshold: null,
    thresholdText: "Descriptivo",
    origin: "Sin umbral en el anteproyecto.",
    decision: "Las ayudas sin valoración (ignoradas) se reportan aparte.",
    automatic: true,
    chart: "Barras apiladas: útil, no útil, sin valorar.",
    jira: ["A3.2"],
  },
  {
    id: "U4",
    name: "Cambios del tutor aplicados en VS Code",
    dimension: "ux",
    objective: "OE3",
    primary: false,
    question: "¿Los estudiantes usan las sugerencias del editor?",
    formula: "suggestion_completion_applied / vscode_suggestion_shown.",
    unit: "%",
    window: "Piloto completo.",
    sources: ["telemetria"],
    events: ["vscode_suggestion_shown", "suggestion_completion_applied"],
    threshold: null,
    thresholdText: "Descriptivo",
    origin: "Sin umbral en el anteproyecto.",
    decision: "Una aplicación alta no es buena por sí sola: se lee junto con P1 y P6.",
    automatic: true,
    chart: "Número en la tabla de KPIs.",
    jira: ["A3.2", "A10.8"],
  },
  {
    id: "U5",
    name: "Respuesta de la encuesta",
    dimension: "ux",
    objective: "OE3",
    primary: false,
    question: "¿Cuántos participantes respondieron la encuesta?",
    formula: "Encuestas válidas / participantes con consentimiento.",
    unit: "%",
    window: "Al final del piloto.",
    sources: ["encuesta", "asistencia"],
    events: [],
    threshold: null,
    thresholdText: "Descriptivo",
    origin: "Sin umbral en el anteproyecto.",
    decision: "Con menos del 70 % se discute el sesgo de no respuesta en los resultados.",
    automatic: true,
    chart: "Número en la tabla de KPIs.",
    jira: ["A3.2", "A14.3"],
  },

  // --- Pedagógicos (A3.2) -----------------------------------------------------
  {
    id: "P1",
    name: "Reducción del tiempo hasta desbloqueo",
    dimension: "pedagogico",
    objective: "OE3",
    primary: true,
    question: "¿El tutor acorta el tiempo que un estudiante pasa atascado en un error?",
    formula: "1 − (mediana, entre estudiantes, de su mediana con tutor / mediana, entre estudiantes, de su mediana sin tutor). Un episodio va de la aparición del error a su desaparición (blocking_resolved.durationMs) y solo cuenta si el error llegó a bloqueo (blocking_detected). Solo estudiantes con episodios resueltos en las dos condiciones. Prueba de Wilcoxon de rangos con signo sobre las medianas pareadas.",
    unit: "%",
    window: "Bloques del piloto (condición vigente al empezar el episodio).",
    sources: ["telemetria"],
    events: ["blocking_detected", "blocking_resolved"],
    threshold: { op: ">=", value: 20 },
    thresholdText: "≥ 20 %",
    origin: "Anteproyecto 5.4 (tiempo hasta desbloqueo −20 %).",
    decision: "Línea base: el mismo estudiante sin tutor (diseño intra-sujeto AB/BA, 24 de septiembre de 2026). Se excluyen los episodios que cruzan un cambio de bloque; los corregidos desde otro archivo entran (cota superior) y se reporta el resultado sin ellos. Fuente: VS Code (el overlay no cierra episodios).",
    automatic: true,
    chart: "Puntos pareados por estudiante (sin tutor → con tutor) y caja por condición; tabla por cohorte para ver el efecto de orden.",
    jira: ["A3.2", "A3.3", "A14.4"],
  },
  {
    id: "P2",
    name: "Episodios de bloqueo resueltos",
    dimension: "pedagogico",
    objective: "OE3",
    primary: false,
    question: "¿Cuántos bloqueos terminan resueltos en cada condición?",
    formula: "Episodios con blocking_resolved / episodios con blocking_detected, por condición.",
    unit: "%",
    window: "Bloques del piloto.",
    sources: ["telemetria"],
    events: ["blocking_detected", "blocking_resolved"],
    threshold: null,
    thresholdText: "Descriptivo (acompaña a P1)",
    origin: "Sin umbral en el anteproyecto.",
    decision: "Un episodio sin cierre queda censurado: no entra en la mediana de P1 y se cuenta aquí.",
    automatic: true,
    chart: "Barras por condición.",
    jira: ["A3.2", "A14.4"],
  },
  {
    id: "P3",
    name: "Participación",
    dimension: "pedagogico",
    objective: "OE3",
    primary: false,
    question: "¿Cuántos participantes completaron las dos condiciones?",
    formula: "Estudiantes con actividad registrada en los dos bloques (con y sin tutor) / estudiantes con consentimiento.",
    unit: "%",
    window: "Piloto completo.",
    sources: ["telemetria", "asistencia"],
    events: ["(eventos con pilot_condition)"],
    threshold: { op: ">=", value: 70 },
    thresholdText: "≥ 70 %",
    origin: "Anteproyecto 5.4 (participación ≥ 70 %).",
    decision: "El número de consentimientos se registra en el plan del piloto (sin nombres).",
    automatic: true,
    chart: "Número en la tabla de KPIs.",
    jira: ["A3.2", "A14.1"],
  },
  {
    id: "P4",
    name: "Percepción de apoyo al aprendizaje",
    dimension: "pedagogico",
    objective: "OE3",
    primary: false,
    question: "¿Los estudiantes sienten que el tutor los ayudó a aprender y no solo a terminar?",
    formula: "Promedio de los ítems PA1 a PA5 de la encuesta final (1 a 5), primero por persona.",
    unit: "/5",
    window: "Al final del piloto.",
    sources: ["encuesta"],
    events: [],
    threshold: { op: ">=", value: 4 },
    thresholdText: "≥ 4,0 / 5",
    origin: "Anteproyecto 5.4 (percepción ≥ 4/5).",
    decision: "Una persona cuenta si respondió al menos 3 de los 5 ítems.",
    automatic: true,
    chart: "Barras divergentes por ítem.",
    jira: ["A3.2", "A13.2"],
  },
  {
    id: "P5",
    name: "Mejoras críticas implementadas",
    dimension: "pedagogico",
    objective: "OE3",
    primary: false,
    question: "¿Se corrigió lo importante que mostró el piloto?",
    formula: "Mejoras críticas implementadas / mejoras críticas identificadas en los hallazgos (A14.5).",
    unit: "%",
    window: "Después del piloto.",
    sources: ["registro"],
    events: [],
    threshold: { op: ">=", value: 65 },
    thresholdText: "≥ 65 %",
    origin: "Anteproyecto 5.4.",
    decision: "5.4 dice ≥ 65 % y A13 ≥ 70 %; manda 5.4.",
    automatic: false,
    chart: "Tabla de hallazgos con su estado.",
    jira: ["A3.2", "A14.5"],
  },
  {
    id: "P6",
    name: "Cumplimiento del límite anti-solución",
    dimension: "pedagogico",
    objective: "OE2",
    primary: false,
    question: "¿Todo cambio de código aplicado pasó por la política del docente?",
    formula: "1 − (cambios aplicados sin verificación previa / cambios aplicados), con la regla I6.",
    unit: "%",
    window: "Piloto completo.",
    sources: ["telemetria"],
    events: ["code_application_checked", "suggestion_completion_applied"],
    threshold: { op: "=", value: 100 },
    thresholdText: "= 100 %",
    origin: "Anteproyecto (A2 y 7.1: nunca la solución completa).",
    decision: "Los recortes del guardarraíl (código más largo que el límite de la etapa) se reportan aparte como evidencia de que el límite actuó.",
    automatic: true,
    chart: "Número en la tabla de KPIs.",
    jira: ["A3.2", "A10.2", "A10.8"],
  },
  {
    id: "P7",
    name: "Bloqueos de la política y uso por etapa",
    dimension: "pedagogico",
    objective: "OE2",
    primary: false,
    question: "¿Qué tipo de ayuda dio el tutor y cuántas bloqueó la política?",
    formula: "Distribución de tutor_decision por etapa de ayuda y tipo de intervención; porcentaje bloqueado por la política sin contar el bloque sin tutor.",
    unit: "%",
    window: "Piloto completo; por canal.",
    sources: ["telemetria"],
    events: ["tutor_decision"],
    threshold: null,
    thresholdText: "Descriptivo",
    origin: "Sin umbral en el anteproyecto.",
    decision: "Las decisiones con reason_code = pilot_no_tutor no son bloqueos de la política: son la condición sin tutor.",
    automatic: true,
    chart: "Barras apiladas por etapa y canal.",
    jira: ["A3.2", "A9.8"],
  },
  {
    id: "P8",
    name: "Aciertos en el mini-quiz",
    dimension: "pedagogico",
    objective: "OE3",
    primary: false,
    question: "¿Los estudiantes entienden el cambio que aceptaron?",
    formula: "Respuestas correctas / respuestas del mini-quiz.",
    unit: "%",
    window: "Piloto completo.",
    sources: ["quices"],
    events: [],
    threshold: null,
    thresholdText: "Descriptivo",
    origin: "Sin umbral en el anteproyecto.",
    decision: "Se exporta con npm run piloto:dataset (tabla student_quizzes con el actor seudonimizado).",
    automatic: true,
    chart: "Número en la tabla de KPIs.",
    jira: ["A3.2", "A8.5"],
  },
];

const KPI_BY_ID = new Map(KPI_CATALOG.map((kpi) => [kpi.id, kpi]));

export function findKpi(id: string) {
  const kpi = KPI_BY_ID.get(id);
  if (!kpi) throw new Error(`KPI desconocido: ${id}`);
  return kpi;
}

/** Compara un valor con el umbral; null si el KPI es descriptivo o no hay valor. */
export function meetsThreshold(kpi: Pick<KpiDefinition, "threshold">, value: number | null) {
  if (!kpi.threshold || value === null || !Number.isFinite(value)) return null;
  const { op, value: target } = kpi.threshold;
  if (op === "<=") return value <= target + 1e-9;
  if (op === ">=") return value >= target - 1e-9;
  return Math.abs(value - target) < 1e-9;
}

/**
 * Qué se mira y cada cuánto (A3.6). El monitor y el informe usan estas
 * mismas listas.
 */
export const KPI_REPORT_PLAN = [
  {
    moment: "Durante cada sesión (monitor, cada 30 s)",
    how: "npm run piloto:monitor",
    kpis: ["T1", "T3", "T4", "T5"],
    extra: "Worker vivo, estudiantes activos en los últimos 5 minutos, eventos por minuto, bloque vigente y alertas.",
  },
  {
    moment: "Al cerrar cada sesión",
    how: "npm run piloto:dataset y npm run piloto:analisis sobre la fecha",
    kpis: ["T1", "T2", "T3", "T4", "T5", "T6", "T9", "P2", "P7"],
    extra: "Informe corto de la sesión para ajustar la siguiente (sin cambiar el tutor a mitad del piloto).",
  },
  {
    moment: "Al terminar el piloto",
    how: "npm run piloto:analisis con la encuesta y el plan",
    kpis: KPI_CATALOG.map((kpi) => kpi.id),
    extra: "Informe completo con gráficas, trazabilidad KPI → hallazgo → evidencia y los KPIs manuales.",
  },
];
